module.exports = Demo;

function Demo(){
  this.el = document.createElement('div');
  this.el.innerHTML = 'This is generated by JavaScript';
  document.body.appendChild(this.el);
  this.el.style.top = (window.innerHeight - this.el.clientHeight) / 2 + 'px';
}

